---
title: "read SST behavioral data"
author: "Ben Smith"
date: "9/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(R.matlab)#install.packages("R.matlab")
library(dplyr)
library(stringr)

Sys.setenv(R_CONFIG_ACTIVE = Sys.info()["nodename"])

#data_path <- "../../../files/data/"
data_path <-config::get("dev_analysis_data_dir")
dev_scripts_path <- config::get("dev_scripts_path")



dropbox_path <- config::get("dropbox_path")
sst_on_dropbox <- paste0(dropbox_path, "/Berkman Lab/Devaluation/Tasks/SST_DEV")

```   



```{r}
raw_full_duration_file <- readr::read_csv(paste0(
  dev_scripts_path,
  "fMRI/fx/multiconds/SST/full_duration_multicond_out.csv"
  )
)

# old_behavioral_format <- readr::read_csv(file = paste0(data_path,"sst_behavioral_data_all_old.csv"))

```



```{r}
#this was written because the preceding data pipeline uses different labels to the parts that come after this, due to a change in the pipeline:
#previously the data was directly exported from the mat files in this Rmd.
#this is now done in the multiconds file.
study_df <- raw_full_duration_file %>% mutate(
  subject_id=paste0("DEV",subject_id),
  runid=1,
  go_no_go_condition_label = case_when(
        go_no_go_condition == 0 ~ "Go",
        go_no_go_condition == 1 ~ "Stop",
        go_no_go_condition == 2 ~ "Cue",
        TRUE ~ as.character(NA)
      )
  ) %>% mutate(
    condition = case_when(
        go_no_go_condition == 0 & reaction_time!=0 ~ "CorrectGo",
        go_no_go_condition == 0 & reaction_time==0 ~ "FailedGo",
        go_no_go_condition == 1 & reaction_time!=0 ~ "FailedStop",
        go_no_go_condition == 1 & reaction_time==0 ~ "CorrectStop",
        go_no_go_condition == 2 ~ "Cue",
        TRUE ~ as.character(NA)
      )
  ) %>%
    rename(onset=trial_start_time,subid=subject_id,waveid=wave_number)


readr::write_csv(study_df,file = paste0(data_path,"sst_behavioral_data_all_via_multiconds.csv"))
```


```{r}
# fname <- "DEV004_3_SST1.mat"
# run_mat_file <- readMat(paste0(behavioral_data_filepath,fname))
```

```{r}
#now we get summary statistics for each subject:
#direction errors, proportion of successful stops, reaction time on Go trials, and stop signal reaction time (SSRT).
#add runid to the group_by clause to group by run; but for our purposes we are happy to count across run!

condition_count <- study_df %>% group_by(subid,condition) %>% count() %>% ungroup()
go_trial_mean_reaction_time <- study_df %>% group_by(subid) %>% filter(condition=="CorrectGo" | condition=="FailedGo") %>% summarise(go_trial_reaction_time = mean(reaction_time)) %>% ungroup()

stop_signal_mean_reaction_time <- study_df %>% group_by(subid) %>% filter(condition=="CorrectStop") %>% summarise(raw_stop_signal_duration = mean(reaction_time)) %>% ungroup()

prop_successful_stops <- condition_count %>% group_by(subid) %>% 
  tidyr::spread(key = "condition",value="n") %>%
  mutate(prop_successful_stops=CorrectStop/(CorrectStop+FailedStop)) %>% ungroup()

for(cname in c("CorrectGo","CorrectStop","FailedGo","FailedStop")){
  prop_successful_stops[is.na(prop_successful_stops[[cname]]),cname]<-0
}

summary_stats <- prop_successful_stops %>% merge(stop_signal_mean_reaction_time) %>% merge(go_trial_mean_reaction_time)



```

```{r}
summary_stats
```

```{r}

readr::write_csv(summary_stats,file=paste0(data_path,"sst_summary_stats.csv"))

```

```{r}
#now we get summary statistics for each subject:
#direction errors, proportion of successful stops, reaction time on Go trials, and stop signal reaction time (SSRT).
#add runid to the group_by clause to group by run; but for our purposes we are happy to count across run!

condition_count <- study_df %>% group_by(runid,subid,condition) %>% count() %>% ungroup()
go_trial_mean_reaction_time <- study_df %>% group_by(runid,subid) %>% filter(condition=="CorrectGo" | condition=="FailedGo") %>% summarise(go_trial_reaction_time = mean(reaction_time)) %>% ungroup()

stop_signal_mean_reaction_time <- study_df %>% group_by(runid,subid) %>% filter(condition=="CorrectStop") %>% summarise(reaction_time = mean(reaction_time)) %>% ungroup()

prop_successful_stops <- condition_count %>% group_by(runid,subid) %>% 
  tidyr::spread(key = "condition",value="n") %>%
  mutate(prop_successful_stops=CorrectStop/(CorrectStop+FailedStop)) %>% ungroup()

for(cname in c("CorrectGo","CorrectStop","FailedGo","FailedStop")){
  prop_successful_stops[is.na(prop_successful_stops[[cname]]),cname]<-0
}

summary_stats_by_run <- prop_successful_stops %>% merge(stop_signal_mean_reaction_time) %>% merge(go_trial_mean_reaction_time)


```


```{r}

readr::write_csv(summary_stats_by_run,file=paste0(data_path,"sst_summary_stats_by_run.csv"))

```


## now read the SSRT data

Data presummarized by Krista, Bryan, and Dani.

```{r}


presummarized_sst_filepath <- paste0(sst_on_dropbox,"/compiledResults/upToDEV228/varMats/resultVars16.mat")

presummarized_sst_data <-  readMat(presummarized_sst_filepath)
```





```{r}

all_table_longer <- NULL
for (result_item_name in names(presummarized_sst_data)){
  subj_by_wave_table <- data.frame(presummarized_sst_data[[result_item_name]])
  wave_colnames<- paste0("wave",1:ncol(subj_by_wave_table))
  colnames(subj_by_wave_table)<-wave_colnames
  subj_by_wave_table$SubjectLabel <- paste0("DEV",str_pad(as.character(1:nrow(subj_by_wave_table)),3,pad="0"))
  
  table_longer <- subj_by_wave_table %>% tidyr::pivot_longer(cols=wave_colnames,names_to="wave")
  table_longer$value_type <- result_item_name
  if(is.null(all_table_longer)){
    all_table_longer <- table_longer
  }else{
    all_table_longer <- rbind(all_table_longer,table_longer)
  }
}

all_table_longer$value_type <- sub(".results","",all_table_longer$value_type)

presummarized_data_all_raw <- all_table_longer %>% tidyr::pivot_wider(id_cols=c("SubjectLabel","wave"),values_from="value",names_from="value_type")

row_na_count<-apply(presummarized_data_all_raw,1,function(r){sum(is.na(r))})
row_without_values <- max(row_na_count)==row_na_count

presummarized_data_all <- presummarized_data_all_raw[row_without_values==FALSE,]

presummarized_data_all$wave <-as.integer(sub("wave","",presummarized_data_all$wave))
```



```{r}

readr::write_csv(presummarized_data_all,file=paste0(data_path,"sst_pre_analyzed_stats.csv"))

```





