---
title: "read SST behavioral data"
author: "Ben Smith"
date: "9/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(R.matlab)#install.packages("R.matlab")
library(dplyr)
library(stringr)
library(stringi)

Sys.setenv(R_CONFIG_ACTIVE = Sys.info()["nodename"])

#data_path <- "../../../files/data/"
data_path <-config::get("dev_analysis_data_dir")
dev_scripts_path <- config::get("dev_scripts_path")



dropbox_path <- config::get("dropbox_path")
sst_on_dropbox <- paste0(dropbox_path, "/Berkman Lab/Devaluation/Tasks/SST_DEV")

input_mat_path =config::get("input_mat_path")

```   




```{r}
get_run_df <- function(run_mat_file){
  conditions <- unlist(run_mat_file$names)
  run_df <- NULL
  for (c_i in 1:length(conditions)){
    print(paste(length(run_mat_file$duration[[c_i]][[1]]),length(run_mat_file$onsets[[c_i]][[1]])))
    #need to handle cases where the lengths are zero
    if(length(run_mat_file$duration[[c_i]][[1]])!=length(run_mat_file$onsets[[c_i]][[1]])){
      stop("found different length duration and onset. these should be the same.")
    }
    if(length(run_mat_file$duration[[c_i]][[1]])==0){
      #no items for this condition  
      print(paste("no events found for condition",conditions[[c_i]]))
      next
    }
    
    condition_df <- data.frame(onset=run_mat_file$onsets[[c_i]][[1]],duration=run_mat_file$duration[[c_i]][[1]],condition=conditions[[c_i]])
    if (is.null(run_df)){
      run_df <- condition_df
    }else{
      run_df <- rbind(run_df,condition_df)
    }
  }
  
  run_df <- run_df %>% arrange(onset)
  return(run_df)
}
```


```{r}
get_run_def_from_mat_filepath <- function(filepath){
  run_mat_file <- readMat(filepath)
  run_df <- get_run_df(run_mat_file)
  return(run_df)
}
```

The code below reads in raw data from the SST task
```{r}
raw_behavioral_data_filepath <- paste0(sst_on_dropbox,"/output/")
fname_list <- list.files(raw_behavioral_data_filepath,pattern = "DEV\\d*\\_run\\d\\_.*\\.mat")
subj_ids <- unique(str_match(fname_list,"(DEV\\d{3})_.*")[,2])
study_df_list <- list()
#loop through each subject because the waves are not pre-labelled. this way we can control the number of runs per subject.
for (subj in subj_ids){
#subj<-subj_ids[[1]]
  if(subj!=subj_ids[[1]]){cat(", ")}
  cat(paste0(subj))
  subj_fnames <- sort(fname_list[str_detect(fname_list,subj)])
  for(fname in subj_fnames){
    #fname<-fname_list[[1]]
    finfo <- str_match(fname,"(DEV\\d{3})_run(\\d)_(\\d*-[a-zA-Z]*-\\d*)\\_(\\d*-\\d*.*)\\.mat")
    subid<-finfo[,2]
    waveid<-finfo[,3]
    run_date<-finfo[,4]
    run_time<-finfo[,5]
    run_mat_file <- readMat(paste0(raw_behavioral_data_filepath,"/",fname))
    seeker <- data.frame(run_mat_file$Seeker)
    #labels taken from:
    #https://github.com/UOSAN/SST_DEV/blob/8e297ff0f003d65157f8a9d8fa28a655f94d75e5/code/experiment/runSST.m#L233
    colnames(seeker) <- c("trial_n","numchunks_reciprocal","go_no_go_condition","arrow_presented","ladder_number","LadderX_SSD_ms","subject_response","ladder_movement","reaction_time","SSD_technical","SSD_observed","onset","arrow_appearance_t","SSD_recorded","trial_duration","time_course","health_condition")
    seeker$subid<-subid
    seeker$waveid<-waveid
    seeker$runid<-1 #there's always only one run.
    seeker$rundatetime<-lubridate::parse_date_time(paste(run_date,run_time),c("%d-%m-%y %H-%M"),tz="US/Pacific")
    seeker <- seeker %>% mutate(
      go_no_go_condition_label = case_when(
            go_no_go_condition == 0 ~ "Go",
            go_no_go_condition == 1 ~ "Stop",
            go_no_go_condition == 2 ~ "Cue",
            TRUE ~ as.character(NA)
          )
      ) %>% mutate(
        condition = case_when(
            go_no_go_condition == 0 & reaction_time!=0 ~ "CorrectGo",
            go_no_go_condition == 0 & reaction_time==0 ~ "FailedGo",
            go_no_go_condition == 1 & reaction_time!=0 ~ "FailedStop",
            go_no_go_condition == 1 & reaction_time==0 ~ "CorrectStop",
            go_no_go_condition == 2 ~ "Cue",
            TRUE ~ as.character(NA)
          )
      )
    study_df_list<-append(study_df_list,list(seeker))
  }
}

study_df <- data.frame(data.table::rbindlist(study_df_list))

```


```{r}
readr::write_csv(study_df,file = paste0(data_path,"sst_behavioral_data_all.csv"))

```


```{r}

#now we get summary statistics for each subject:
#direction errors, proportion of successful stops, reaction time on Go trials, and stop signal reaction time (SSRT).
#add runid to the group_by clause to group by run; but for our purposes we are happy to count across run!

condition_count <- study_df %>% group_by(subid,condition) %>% count() %>% ungroup()
go_trial_mean_reaction_time <- study_df %>% group_by(subid) %>% filter(condition=="CorrectGo" | condition=="FailedGo") %>% summarise(go_trial_reaction_time = mean(reaction_time)) %>% ungroup()

stop_signal_mean_reaction_time <- study_df %>% group_by(subid) %>% filter(condition=="CorrectStop") %>% summarise(raw_stop_signal_duration = mean(reaction_time)) %>% ungroup()

prop_successful_stops <- condition_count %>% group_by(subid) %>% 
  tidyr::spread(key = "condition",value="n") %>%
  mutate(prop_successful_stops=CorrectStop/(CorrectStop+FailedStop)) %>% ungroup()

for(cname in c("CorrectGo","CorrectStop","FailedGo","FailedStop")){
  prop_successful_stops[is.na(prop_successful_stops[[cname]]),cname]<-0
}


summary_stats <- prop_successful_stops %>% merge(stop_signal_mean_reaction_time) %>% merge(go_trial_mean_reaction_time)



```

```{r}
summary_stats
```

```{r}

readr::write_csv(summary_stats,file=paste0(data_path,"sst_summary_stats.csv"))

```

```{r}
#now we get summary statistics for each subject:
#direction errors, proportion of successful stops, reaction time on Go trials, and stop signal reaction time (SSRT).
#add runid to the group_by clause to group by run; but for our purposes we are happy to count across run!

condition_count <- study_df %>% group_by(runid,subid,condition) %>% count() %>% ungroup()
go_trial_mean_reaction_time <- study_df %>% group_by(runid,subid) %>% filter(condition=="CorrectGo" | condition=="FailedGo") %>% summarise(go_trial_reaction_time = mean(reaction_time)) %>% ungroup()

stop_signal_mean_reaction_time <- study_df %>% group_by(runid,subid) %>% filter(condition=="CorrectStop") %>% summarise(reaction_time = mean(reaction_time)) %>% ungroup()

prop_successful_stops <- condition_count %>% group_by(runid,subid) %>% 
  tidyr::spread(key = "condition",value="n") %>%
  mutate(prop_successful_stops=CorrectStop/(CorrectStop+FailedStop)) %>% ungroup()

for(cname in c("CorrectGo","CorrectStop","FailedGo","FailedStop")){
  prop_successful_stops[is.na(prop_successful_stops[[cname]]),cname]<-0
}

summary_stats_by_run <- prop_successful_stops %>% merge(stop_signal_mean_reaction_time) %>% merge(go_trial_mean_reaction_time)


```


```{r}

readr::write_csv(summary_stats_by_run,file=paste0(data_path,"sst_summary_stats_by_run.csv"))

```


## now read the SSRT data

Data presummarized by Krista, Bryan, and Dani.

```{r}


presummarized_sst_filepath <- paste0(sst_on_dropbox,"/compiledResults/upToDEV228/varMats/resultVars16.mat")

presummarized_sst_data <-  readMat(presummarized_sst_filepath)
```





```{r}

all_table_longer <- NULL
for (result_item_name in names(presummarized_sst_data)){
  subj_by_wave_table <- data.frame(presummarized_sst_data[[result_item_name]])
  wave_colnames<- paste0("wave",1:ncol(subj_by_wave_table))
  colnames(subj_by_wave_table)<-wave_colnames
  subj_by_wave_table$SubjectLabel <- paste0("DEV",str_pad(as.character(1:nrow(subj_by_wave_table)),3,pad="0"))
  
  table_longer <- subj_by_wave_table %>% tidyr::pivot_longer(cols=wave_colnames,names_to="wave")
  table_longer$value_type <- result_item_name
  if(is.null(all_table_longer)){
    all_table_longer <- table_longer
  }else{
    all_table_longer <- rbind(all_table_longer,table_longer)
  }
}

all_table_longer$value_type <- sub(".results","",all_table_longer$value_type)

presummarized_data_all_raw <- all_table_longer %>% tidyr::pivot_wider(id_cols=c("SubjectLabel","wave"),values_from="value",names_from="value_type")

row_na_count<-apply(presummarized_data_all_raw,1,function(r){sum(is.na(r))})
row_without_values <- max(row_na_count)==row_na_count

presummarized_data_all <- presummarized_data_all_raw[row_without_values==FALSE,]

presummarized_data_all$wave <-as.integer(sub("wave","",presummarized_data_all$wave))
```



```{r}

readr::write_csv(presummarized_data_all,file=paste0(data_path,"sst_pre_analyzed_stats.csv"))

```





